CREATE TABLE `DROIDCLIC_clics` (
`id` int(11) DEFAULT NULL,
`titol` varchar(255) DEFAULT NULL,
`descripcio` varchar(2048) DEFAULT NULL,
`lang` varchar(2) DEFAULT NULL,
`autors` varchar(255) DEFAULT NULL,
`llicencia` varchar(255) DEFAULT NULL,
`nivell` varchar(255) DEFAULT NULL,
`area` varchar(255) DEFAULT NULL,
`area_lleng` bit(1) NOT NULL DEFAULT b'0',
`area_mat` bit(1) NOT NULL DEFAULT b'0',
`area_soc` bit(1) NOT NULL DEFAULT b'0',
`area_exp` bit(1) NOT NULL DEFAULT b'0',
`area_mus` bit(1) NOT NULL DEFAULT b'0',
`area_vip` bit(1) NOT NULL DEFAULT b'0',
`area_ef` bit(1) NOT NULL DEFAULT b'0',
`area_tec` bit(1) NOT NULL DEFAULT b'0',
`area_div` bit(1) NOT NULL DEFAULT b'0',

`nivel_all` bit(1) NOT NULL DEFAULT b'0',
`nivel_INF` bit(1) NOT NULL DEFAULT b'0',
`nivel_PRI` bit(1) NOT NULL DEFAULT b'0',
`nivel_SEC` bit(1) NOT NULL DEFAULT b'0',
`nivel_BTX` bit(1) NOT NULL DEFAULT b'0',

`logoUrl` varchar(255) DEFAULT NULL,
`urlBase` varchar(255) DEFAULT NULL,
`inst` varchar(255) DEFAULT NULL,
`clicPrincipal` varchar(255) DEFAULT NULL,
`clicsAdicionals` varchar(1024) DEFAULT NULL,
`tipusActivitats` varchar(1024) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
